version: '3.8'

services:
  cotex-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
    environment:
      - PORT=8001
    restart: unless-stopped
    container_name: cotex-ai-agent